# Generated by Django 2.1.7 on 2019-04-21 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='score',
            field=models.PositiveIntegerField(default=0, verbose_name='score'),
        ),
        migrations.AddField(
            model_name='generalprofile',
            name='credit',
            field=models.IntegerField(default=0, verbose_name='credit'),
        ),
        migrations.AddField(
            model_name='passenger',
            name='score',
            field=models.PositiveIntegerField(default=0, verbose_name='score'),
        ),
        migrations.AddField(
            model_name='transmit',
            name='score',
            field=models.PositiveIntegerField(default=0, verbose_name='score'),
        ),
    ]
