# Generated by Django 2.1.7 on 2019-04-20 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='back_seat_price',
            field=models.PositiveIntegerField(default=1, verbose_name='back_seat_price'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='front_seat_price',
            field=models.PositiveIntegerField(default=1, verbose_name='front_seat_price'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='is_dispatcher',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trip',
            name='item_capacity',
            field=models.PositiveIntegerField(default=1, verbose_name='Item Capacity'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='passenger_capacity',
            field=models.PositiveSmallIntegerField(choices=[(1, 'one capacity'), (2, 'two capacity'), (3, 'three capacity'), (4, 'four capacity')], default=1, verbose_name='passenger_capacity'),
            preserve_default=False,
        ),
    ]
