# Generated by Django 2.1.7 on 2019-04-21 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0002_auto_20190420_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='state',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='state'),
        ),
    ]
