# Generated by Django 2.1.7 on 2019-04-21 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0004_seat_type_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='type_creator',
        ),
        migrations.AddField(
            model_name='trip',
            name='type_creator',
            field=models.PositiveSmallIntegerField(choices=[(1, 'driver'), (2, 'passenger')], default=1, verbose_name='creator type'),
            preserve_default=False,
        ),
    ]
