# Generated by Django 2.1.7 on 2019-04-21 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0005_auto_20190421_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='back_seat_price',
            field=models.PositiveIntegerField(null=True, verbose_name='back_seat_price'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='front_seat_price',
            field=models.PositiveIntegerField(null=True, verbose_name='front_seat_price'),
        ),
    ]
