# Generated by Django 2.1.7 on 2019-04-21 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0006_auto_20190421_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='item_capacity',
            field=models.PositiveIntegerField(null=True, verbose_name='Item Capacity'),
        ),
    ]
