# Generated by Django 2.1.7 on 2019-04-21 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0007_auto_20190421_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='passenger_capacity',
            field=models.PositiveSmallIntegerField(choices=[(1, 'one capacity'), (2, 'two capacity'), (3, 'three capacity'), (4, 'four capacity')], null=True, verbose_name='passenger_capacity'),
        ),
    ]
